---
abstract: 'Convert Perl5 source to compile under Perl6.'
author:
  - 'Jeffrey Goff <drforr@pobox.com>'
build_requires:
  Test::Deep: '0'
  Test::More: '0'
  lib: '0'
configure_requires:
  Module::Build: '0.4024'
dynamic_config: 1
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-ToPerl6
no_index:
  directory:
    - doc
    - inc
    - tools
  file:
    - TODO.pod
provides:
  Perl::ToPerl6:
    file: lib/Perl/ToPerl6.pm
    version: '0.02'
  Perl::ToPerl6::Annotation:
    file: lib/Perl/ToPerl6/Annotation.pm
    version: '0.02'
  Perl::ToPerl6::Command:
    file: lib/Perl/ToPerl6/Command.pm
    version: '0.02'
  Perl::ToPerl6::Config:
    file: lib/Perl/ToPerl6/Config.pm
    version: '0.02'
  Perl::ToPerl6::Document:
    file: lib/Perl/ToPerl6/Document.pm
    version: '0.02'
  Perl::ToPerl6::Exception:
    file: lib/Perl/ToPerl6/Exception.pm
    version: '0.02'
  Perl::ToPerl6::Exception::AggregateConfiguration:
    file: lib/Perl/ToPerl6/Exception/AggregateConfiguration.pm
    version: '0.02'
  Perl::ToPerl6::Exception::Configuration:
    file: lib/Perl/ToPerl6/Exception/Configuration.pm
    version: '0.02'
  Perl::ToPerl6::Exception::Configuration::Generic:
    file: lib/Perl/ToPerl6/Exception/Configuration/Generic.pm
    version: '0.02'
  Perl::ToPerl6::Exception::Configuration::NonExistentTransformer:
    file: lib/Perl/ToPerl6/Exception/Configuration/NonExistentTransformer.pm
    version: '0.02'
  Perl::ToPerl6::Exception::Configuration::Option:
    file: lib/Perl/ToPerl6/Exception/Configuration/Option.pm
    version: '0.02'
  Perl::ToPerl6::Exception::Configuration::Option::Global:
    file: lib/Perl/ToPerl6/Exception/Configuration/Option/Global.pm
    version: '0.02'
  Perl::ToPerl6::Exception::Configuration::Option::Global::ExtraParameter:
    file: lib/Perl/ToPerl6/Exception/Configuration/Option/Global/ExtraParameter.pm
    version: '0.02'
  Perl::ToPerl6::Exception::Configuration::Option::Global::ParameterValue:
    file: lib/Perl/ToPerl6/Exception/Configuration/Option/Global/ParameterValue.pm
    version: '0.02'
  Perl::ToPerl6::Exception::Configuration::Option::Transformer:
    file: lib/Perl/ToPerl6/Exception/Configuration/Option/Transformer.pm
    version: '0.02'
  Perl::ToPerl6::Exception::Configuration::Option::Transformer::ExtraParameter:
    file: lib/Perl/ToPerl6/Exception/Configuration/Option/Transformer/ExtraParameter.pm
    version: '0.02'
  Perl::ToPerl6::Exception::Configuration::Option::Transformer::ParameterValue:
    file: lib/Perl/ToPerl6/Exception/Configuration/Option/Transformer/ParameterValue.pm
    version: '0.02'
  Perl::ToPerl6::Exception::Fatal:
    file: lib/Perl/ToPerl6/Exception/Fatal.pm
    version: '0.02'
  Perl::ToPerl6::Exception::Fatal::Generic:
    file: lib/Perl/ToPerl6/Exception/Fatal/Generic.pm
    version: '0.02'
  Perl::ToPerl6::Exception::Fatal::Internal:
    file: lib/Perl/ToPerl6/Exception/Fatal/Internal.pm
    version: '0.02'
  Perl::ToPerl6::Exception::Fatal::TransformerDefinition:
    file: lib/Perl/ToPerl6/Exception/Fatal/TransformerDefinition.pm
    version: '0.02'
  Perl::ToPerl6::Exception::IO:
    file: lib/Perl/ToPerl6/Exception/IO.pm
    version: '0.02'
  Perl::ToPerl6::Exception::Parse:
    file: lib/Perl/ToPerl6/Exception/Parse.pm
    version: '0.02'
  Perl::ToPerl6::OptionsProcessor:
    file: lib/Perl/ToPerl6/OptionsProcessor.pm
    version: '0.02'
  Perl::ToPerl6::ProfilePrototype:
    file: lib/Perl/ToPerl6/ProfilePrototype.pm
    version: '0.02'
  Perl::ToPerl6::Statistics:
    file: lib/Perl/ToPerl6/Statistics.pm
    version: '0.02'
  Perl::ToPerl6::TestUtils:
    file: lib/Perl/ToPerl6/TestUtils.pm
    version: '0.02'
  Perl::ToPerl6::Theme:
    file: lib/Perl/ToPerl6/Theme.pm
    version: '0.02'
  Perl::ToPerl6::ThemeListing:
    file: lib/Perl/ToPerl6/ThemeListing.pm
    version: '0.02'
  Perl::ToPerl6::Transformation:
    file: lib/Perl/ToPerl6/Transformation.pm
    version: '0.02'
  Perl::ToPerl6::Transformer:
    file: lib/Perl/ToPerl6/Transformer.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::Arrays::FormatArrayQws:
    file: lib/Perl/ToPerl6/Transformer/Arrays/FormatArrayQws.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::BasicTypes::Integers::FormatBinaryLiterals:
    file: lib/Perl/ToPerl6/Transformer/BasicTypes/Integers/FormatBinaryLiterals.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::BasicTypes::Integers::FormatHexLiterals:
    file: lib/Perl/ToPerl6/Transformer/BasicTypes/Integers/FormatHexLiterals.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::BasicTypes::Integers::FormatOctalLiterals:
    file: lib/Perl/ToPerl6/Transformer/BasicTypes/Integers/FormatOctalLiterals.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::BasicTypes::Rationals::FormatRationals:
    file: lib/Perl/ToPerl6/Transformer/BasicTypes/Rationals/FormatRationals.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::BasicTypes::Strings::FormatHereDocs:
    file: lib/Perl/ToPerl6/Transformer/BasicTypes/Strings/FormatHereDocs.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::BasicTypes::Strings::FormatRegexp:
    file: lib/Perl/ToPerl6/Transformer/BasicTypes/Strings/FormatRegexp.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::BasicTypes::Strings::FormatShellStrings:
    file: lib/Perl/ToPerl6/Transformer/BasicTypes/Strings/FormatShellStrings.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::BasicTypes::Strings::Interpolation:
    file: lib/Perl/ToPerl6/Transformer/BasicTypes/Strings/Interpolation.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::Builtins::FormatPrint:
    file: lib/Perl/ToPerl6/Transformer/Builtins/FormatPrint.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::CompoundStatements::AddWhitespace:
    file: lib/Perl/ToPerl6/Transformer/CompoundStatements/AddWhitespace.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::CompoundStatements::FormatConditionals:
    file: lib/Perl/ToPerl6/Transformer/CompoundStatements/FormatConditionals.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::CompoundStatements::FormatGivenWhens:
    file: lib/Perl/ToPerl6/Transformer/CompoundStatements/FormatGivenWhens.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::CompoundStatements::FormatLoops:
    file: lib/Perl/ToPerl6/Transformer/CompoundStatements/FormatLoops.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::CompoundStatements::FormatMapGreps:
    file: lib/Perl/ToPerl6/Transformer/CompoundStatements/FormatMapGreps.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::CompoundStatements::FormatUntils:
    file: lib/Perl/ToPerl6/Transformer/CompoundStatements/FormatUntils.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::CompoundStatements::RenameForeach:
    file: lib/Perl/ToPerl6/Transformer/CompoundStatements/RenameForeach.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::CompoundStatements::SwapForArguments:
    file: lib/Perl/ToPerl6/Transformer/CompoundStatements/SwapForArguments.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::FormatConstants:
    file: lib/Perl/ToPerl6/Transformer/FormatConstants.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::FormatSpecialLiterals:
    file: lib/Perl/ToPerl6/Transformer/FormatSpecialLiterals.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::Operators::AddWhitespace:
    file: lib/Perl/ToPerl6/Transformer/Operators/AddWhitespace.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::Operators::FormatCircumfixOperators:
    file: lib/Perl/ToPerl6/Transformer/Operators/FormatCircumfixOperators.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::Operators::FormatOperators:
    file: lib/Perl/ToPerl6/Transformer/Operators/FormatOperators.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::Packages::FormatPackageDeclarations:
    file: lib/Perl/ToPerl6/Transformer/Packages/FormatPackageDeclarations.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::Packages::FormatPackageUsages:
    file: lib/Perl/ToPerl6/Transformer/Packages/FormatPackageUsages.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::PostfixExpressions::AddWhitespace:
    file: lib/Perl/ToPerl6/Transformer/PostfixExpressions/AddWhitespace.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::Pragmas::FormatPragmas:
    file: lib/Perl/ToPerl6/Transformer/Pragmas/FormatPragmas.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::References::FormatDereferences:
    file: lib/Perl/ToPerl6/Transformer/References/FormatDereferences.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::Regexes::StandardizeDelimiters:
    file: lib/Perl/ToPerl6/Transformer/Regexes/StandardizeDelimiters.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::Regexes::SwapModifiers:
    file: lib/Perl/ToPerl6/Transformer/Regexes/SwapModifiers.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::Subroutines::RemovePrototypes:
    file: lib/Perl/ToPerl6/Transformer/Subroutines/RemovePrototypes.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::Variables::FormatHashKeys:
    file: lib/Perl/ToPerl6/Transformer/Variables/FormatHashKeys.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::Variables::FormatMatchVariables:
    file: lib/Perl/ToPerl6/Transformer/Variables/FormatMatchVariables.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::Variables::FormatSigils:
    file: lib/Perl/ToPerl6/Transformer/Variables/FormatSigils.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::Variables::FormatSpecialVariables:
    file: lib/Perl/ToPerl6/Transformer/Variables/FormatSpecialVariables.pm
    version: '0.02'
  Perl::ToPerl6::Transformer::Variables::ReplaceUndef:
    file: lib/Perl/ToPerl6/Transformer/Variables/ReplaceUndef.pm
    version: '0.02'
  Perl::ToPerl6::TransformerConfig:
    file: lib/Perl/ToPerl6/TransformerConfig.pm
    version: '0.02'
  Perl::ToPerl6::TransformerFactory:
    file: lib/Perl/ToPerl6/TransformerFactory.pm
    version: '0.02'
  Perl::ToPerl6::TransformerListing:
    file: lib/Perl/ToPerl6/TransformerListing.pm
    version: '0.02'
  Perl::ToPerl6::TransformerParameter:
    file: lib/Perl/ToPerl6/TransformerParameter.pm
    version: '0.02'
  Perl::ToPerl6::TransformerParameter::Behavior:
    file: lib/Perl/ToPerl6/TransformerParameter/Behavior.pm
    version: '0.02'
  Perl::ToPerl6::TransformerParameter::Behavior::Boolean:
    file: lib/Perl/ToPerl6/TransformerParameter/Behavior/Boolean.pm
    version: '0.02'
  Perl::ToPerl6::TransformerParameter::Behavior::Enumeration:
    file: lib/Perl/ToPerl6/TransformerParameter/Behavior/Enumeration.pm
    version: '0.02'
  Perl::ToPerl6::TransformerParameter::Behavior::Integer:
    file: lib/Perl/ToPerl6/TransformerParameter/Behavior/Integer.pm
    version: '0.02'
  Perl::ToPerl6::TransformerParameter::Behavior::String:
    file: lib/Perl/ToPerl6/TransformerParameter/Behavior/String.pm
    version: '0.02'
  Perl::ToPerl6::TransformerParameter::Behavior::StringList:
    file: lib/Perl/ToPerl6/TransformerParameter/Behavior/StringList.pm
    version: '0.02'
  Perl::ToPerl6::UserProfile:
    file: lib/Perl/ToPerl6/UserProfile.pm
    version: '0.02'
  Perl::ToPerl6::Utils:
    file: lib/Perl/ToPerl6/Utils.pm
    version: '0.02'
  Perl::ToPerl6::Utils::Constants:
    file: lib/Perl/ToPerl6/Utils/Constants.pm
    version: '0.02'
  Perl::ToPerl6::Utils::DataConversion:
    file: lib/Perl/ToPerl6/Utils/DataConversion.pm
    version: '0.02'
  Perl::ToPerl6::Utils::McCabe:
    file: lib/Perl/ToPerl6/Utils/McCabe.pm
    version: '0.02'
  Perl::ToPerl6::Utils::POD:
    file: lib/Perl/ToPerl6/Utils/POD.pm
    version: '0.02'
  Perl::ToPerl6::Utils::PPI:
    file: lib/Perl/ToPerl6/Utils/PPI.pm
    version: '0.02'
  Perl::ToPerl6::Utils::Perl:
    file: lib/Perl/ToPerl6/Utils/Perl.pm
    version: '0.02'
  Test::Perl::ToPerl6::Transformer:
    file: lib/Test/Perl/ToPerl6/Transformer.pm
    version: '0.01'
requires:
  B::Keywords: '1.05'
  Carp: '0'
  Config::Tiny: '2'
  English: '0'
  Exception::Class: '1.23'
  Exporter: '5.63'
  File::Basename: '0'
  File::Find: '0'
  File::HomeDir: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Spec::Unix: '0'
  File::Temp: '0'
  File::Which: '0'
  Getopt::Long: '0'
  IO::String: '0'
  IPC::Open2: '1'
  List::MoreUtils: '0.19'
  List::Util: '0'
  Module::Pluggable: '3.1'
  PPI: '1.220'
  PPI::Document: '1.220'
  PPI::Document::File: '1.220'
  PPI::Node: '1.220'
  PPI::Token::Quote::Single: '1.220'
  PPI::Token::Whitespace: '1.220'
  PPIx::Regexp: '0.027'
  PPIx::Utilities::Node: '1.001'
  PPIx::Utilities::Statement: '1.001'
  Perl::Tidy: '0'
  Pod::Parser: '0'
  Pod::PlainText: '0'
  Pod::Select: '0'
  Pod::Usage: '0'
  Readonly: '2'
  Scalar::Util: '0'
  String::Format: '1.13'
  Task::Weaken: '0'
  Term::ANSIColor: '2.02'
  Test::Builder: '0.92'
  Text::ParseWords: '3'
  base: '0'
  charnames: '0'
  overload: '0'
  strict: '0'
  version: '0.77'
  warnings: '0'
resources:
  bugtracker: https://github.com/drforr/Perl-ToPerl6/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/drforr/Perl-ToPerl6.git
version: '0.02'
x_authority: cpan:JGOFF
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
