## name match transformed
## parms {}
## failures 0
## cut
/foo/
m/foo/
m<foo>
m/foo/i
m/foo/i if 1
m/foo/i and 1
1 if m/foo/i
1 and m/foo/i
m<foo>i
m<foo>gi
#-->
/foo/
m/foo/
m<foo>
m:i/foo/
m:i/foo/ if 1
m:i/foo/ and 1
1 if m:i/foo/
1 and m:i/foo/
m:i<foo>
m:gi<foo>
## name substitute
## parms {}
## failures 0
## cut
s/foo/bar/
s{foo}<bar>
s(foo)(bar)
s/foo/bar/i
s{foo}<bar>i
s(foo)(bar)i
#-->
s/foo/bar/
s{foo}<bar>
s(foo)(bar)
s:i/foo/bar/
s:i{foo}<bar>
s:i(foo)(bar)
