
=head1 NAME

Perl::Mogrify::TransformerSummary - Descriptions of the Transformer modules included with L<Perl::Mogrify|Perl::Mogrify> itself.


=head1 DESCRIPTION

The following Transformer modules are distributed with Perl::Mogrify. (There are
additional Policies that can be found in add-on distributions.)  The Transformer
modules have been categorized according to the table of contents in Damian
Conway's book B<Perl Best Practices>. Since most coding standards take the
form "do this..." or "don't do that...", I have adopted the convention of
naming each module C<RequireSomething> or C<ProhibitSomething>.  Each Transformer
is listed here with its default severity.  If you don't agree with the default
severity, you can change it in your F<.perlcriticrc> file (try C<perlcritic
--profile-proto> for a starting version).  See the documentation of each
module for its specific details.


=head1 POLICIES

=head2 L<BuiltinFunctions::ProhibitBooleanGrep|Perl::Mogrify::Transformer::BuiltinFunctions::ProhibitBooleanGrep>

Use C<List::MoreUtils::any> instead of C<grep> in boolean context. [Default severity 2]

=head2 L<BuiltinFunctions::ProhibitComplexMappings|Perl::Mogrify::Transformer::BuiltinFunctions::ProhibitComplexMappings>

Map blocks should have a single statement. [Default severity 3]

=head2 L<BuiltinFunctions::ProhibitLvalueSubstr|Perl::Mogrify::Transformer::BuiltinFunctions::ProhibitLvalueSubstr>

Use 4-argument C<substr> instead of writing C<substr($foo, 2, 6) = $bar>. [Default severity 3]

=head2 L<BuiltinFunctions::ProhibitReverseSortBlock|Perl::Mogrify::Transformer::BuiltinFunctions::ProhibitReverseSortBlock>

Forbid $b before $a in sort blocks. [Default severity 1]

=head2 L<BuiltinFunctions::ProhibitSleepViaSelect|Perl::Mogrify::Transformer::BuiltinFunctions::ProhibitSleepViaSelect>

Use L<Time::HiRes|Time::HiRes> instead of something like C<select(undef, undef, undef, .05)>. [Default severity 5]

=head2 L<BuiltinFunctions::ProhibitStringyEval|Perl::Mogrify::Transformer::BuiltinFunctions::ProhibitStringyEval>

Write C<eval { my $foo; bar($foo) }> instead of C<eval "my $foo; bar($foo);">. [Default severity 5]

=head2 L<BuiltinFunctions::ProhibitStringySplit|Perl::Mogrify::Transformer::BuiltinFunctions::ProhibitStringySplit>

Write C<split /-/, $string> instead of C<split '-', $string>. [Default severity 2]

=head2 L<BuiltinFunctions::ProhibitUniversalCan|Perl::Mogrify::Transformer::BuiltinFunctions::ProhibitUniversalCan>

Write C<< eval { $foo->can($name) } >> instead of C<UNIVERSAL::can($foo, $name)>. [Default severity 3]

=head2 L<BuiltinFunctions::ProhibitUniversalIsa|Perl::Mogrify::Transformer::BuiltinFunctions::ProhibitUniversalIsa>

Write C<< eval { $foo->isa($pkg) } >> instead of C<UNIVERSAL::isa($foo, $pkg)>. [Default severity 3]

=head2 L<BuiltinFunctions::ProhibitUselessTopic|Perl::Mogrify::Transformer::BuiltinFunctions::ProhibitUselessTopic>

Don't pass $_ to built-in functions that assume it, or to most filetest operators. [Default severity 2]

=head2 L<BuiltinFunctions::ProhibitVoidGrep|Perl::Mogrify::Transformer::BuiltinFunctions::ProhibitVoidGrep>

Don't use C<grep> in void contexts. [Default severity 3]

=head2 L<BuiltinFunctions::ProhibitVoidMap|Perl::Mogrify::Transformer::BuiltinFunctions::ProhibitVoidMap>

Don't use C<map> in void contexts. [Default severity 3]

=head2 L<BuiltinFunctions::RequireBlockGrep|Perl::Mogrify::Transformer::BuiltinFunctions::RequireBlockGrep>

Write C<grep { /$pattern/ } @list> instead of C<grep /$pattern/, @list>. [Default severity 4]

=head2 L<BuiltinFunctions::RequireBlockMap|Perl::Mogrify::Transformer::BuiltinFunctions::RequireBlockMap>

Write C<map { /$pattern/ } @list> instead of C<map /$pattern/, @list>. [Default severity 4]

=head2 L<BuiltinFunctions::RequireGlobFunction|Perl::Mogrify::Transformer::BuiltinFunctions::RequireGlobFunction>

Use C<glob q{*}> instead of <*>. [Default severity 5]

=head2 L<BuiltinFunctions::RequireSimpleSortBlock|Perl::Mogrify::Transformer::BuiltinFunctions::RequireSimpleSortBlock>

Sort blocks should have a single statement. [Default severity 3]

=head2 L<ClassHierarchies::ProhibitAutoloading|Perl::Mogrify::Transformer::ClassHierarchies::ProhibitAutoloading>

AUTOLOAD methods should be avoided. [Default severity 3]

=head2 L<ClassHierarchies::ProhibitExplicitISA|Perl::Mogrify::Transformer::ClassHierarchies::ProhibitExplicitISA>

Employ C<use base> instead of C<@ISA>. [Default severity 3]

=head2 L<ClassHierarchies::ProhibitOneArgBless|Perl::Mogrify::Transformer::ClassHierarchies::ProhibitOneArgBless>

Write C<bless {}, $class;> instead of just C<bless {};>. [Default severity 5]

=head2 L<CodeLayout::ProhibitHardTabs|Perl::Mogrify::Transformer::CodeLayout::ProhibitHardTabs>

Use spaces instead of tabs. [Default severity 3]

=head2 L<CodeLayout::ProhibitParensWithBuiltins|Perl::Mogrify::Transformer::CodeLayout::ProhibitParensWithBuiltins>

Write C<open $handle, $path> instead of C<open($handle, $path)>. [Default severity 1]

=head2 L<CodeLayout::ProhibitQuotedWordLists|Perl::Mogrify::Transformer::CodeLayout::ProhibitQuotedWordLists>

Write C<qw(foo bar baz)> instead of C<('foo', 'bar', 'baz')>. [Default severity 2]

=head2 L<CodeLayout::ProhibitTrailingWhitespace|Perl::Mogrify::Transformer::CodeLayout::ProhibitTrailingWhitespace>

Don't use whitespace at the end of lines. [Default severity 1]

=head2 L<CodeLayout::RequireConsistentNewlines|Perl::Mogrify::Transformer::CodeLayout::RequireConsistentNewlines>

Use the same newline through the source. [Default severity 4]

=head2 L<CodeLayout::RequireTidyCode|Perl::Mogrify::Transformer::CodeLayout::RequireTidyCode>

Must run code through L<perltidy|perltidy>. [Default severity 1]

=head2 L<CodeLayout::RequireTrailingCommas|Perl::Mogrify::Transformer::CodeLayout::RequireTrailingCommas>

Put a comma at the end of every multi-line list declaration, including the last one. [Default severity 1]

=head2 L<ControlStructures::ProhibitCStyleForLoops|Perl::Mogrify::Transformer::ControlStructures::ProhibitCStyleForLoops>

Write C<for(0..20)> instead of C<for($i=0; $i<=20; $i++)>. [Default severity 2]

=head2 L<ControlStructures::ProhibitCascadingIfElse|Perl::Mogrify::Transformer::ControlStructures::ProhibitCascadingIfElse>

Don't write long "if-elsif-elsif-elsif-elsif...else" chains. [Default severity 3]

=head2 L<ControlStructures::ProhibitDeepNests|Perl::Mogrify::Transformer::ControlStructures::ProhibitDeepNests>

Don't write deeply nested loops and conditionals. [Default severity 3]

=head2 L<ControlStructures::ProhibitLabelsWithSpecialBlockNames|Perl::Mogrify::Transformer::ControlStructures::ProhibitLabelsWithSpecialBlockNames>

Don't use labels that are the same as the special block names. [Default severity 4]

=head2 L<ControlStructures::ProhibitMutatingListFunctions|Perl::Mogrify::Transformer::ControlStructures::ProhibitMutatingListFunctions>

Don't modify C<$_> in list functions. [Default severity 5]

=head2 L<ControlStructures::ProhibitNegativeExpressionsInUnlessAndUntilConditions|Perl::Mogrify::Transformer::ControlStructures::ProhibitNegativeExpressionsInUnlessAndUntilConditions>

Don't use operators like C<not>, C<!~>, and C<le> within C<until> and C<unless>. [Default severity 3]

=head2 L<ControlStructures::ProhibitPostfixControls|Perl::Mogrify::Transformer::ControlStructures::ProhibitPostfixControls>

Write C<if($condition){ do_something() }> instead of C<do_something() if $condition>. [Default severity 2]

=head2 L<ControlStructures::ProhibitUnlessBlocks|Perl::Mogrify::Transformer::ControlStructures::ProhibitUnlessBlocks>

Write C<if(! $condition)> instead of C<unless($condition)>. [Default severity 2]

=head2 L<ControlStructures::ProhibitUnreachableCode|Perl::Mogrify::Transformer::ControlStructures::ProhibitUnreachableCode>

Don't write code after an unconditional C<die, exit, or next>. [Default severity 4]

=head2 L<ControlStructures::ProhibitUntilBlocks|Perl::Mogrify::Transformer::ControlStructures::ProhibitUntilBlocks>

Write C<while(! $condition)> instead of C<until($condition)>. [Default severity 2]

=head2 L<Documentation::PodSpelling|Perl::Mogrify::Transformer::Documentation::PodSpelling>

Check your spelling. [Default severity 1]

=head2 L<Documentation::RequirePackageMatchesPodName|Perl::Mogrify::Transformer::Documentation::RequirePackageMatchesPodName>

The C<=head1 NAME> section should match the package. [Default severity 1]

=head2 L<Documentation::RequirePodAtEnd|Perl::Mogrify::Transformer::Documentation::RequirePodAtEnd>

All POD should be after C<__END__>. [Default severity 1]

=head2 L<Documentation::RequirePodLinksIncludeText|Perl::Mogrify::Transformer::Documentation::RequirePodLinksIncludeText>

Provide text to display with your pod links. [Default severity 2]

=head2 L<Documentation::RequirePodSections|Perl::Mogrify::Transformer::Documentation::RequirePodSections>

Organize your POD into the customary sections. [Default severity 2]

=head2 L<ErrorHandling::RequireCarping|Perl::Mogrify::Transformer::ErrorHandling::RequireCarping>

Use functions from L<Carp|Carp> instead of C<warn> or C<die>. [Default severity 3]

=head2 L<ErrorHandling::RequireCheckingReturnValueOfEval|Perl::Mogrify::Transformer::ErrorHandling::RequireCheckingReturnValueOfEval>

You can't depend upon the value of C<$@>/C<$EVAL_ERROR> to tell whether an C<eval> failed. [Default severity 3]

=head2 L<InputOutput::ProhibitBacktickOperators|Perl::Mogrify::Transformer::InputOutput::ProhibitBacktickOperators>

Discourage stuff like C<@files = `ls $directory`>. [Default severity 3]

=head2 L<InputOutput::ProhibitBarewordFileHandles|Perl::Mogrify::Transformer::InputOutput::ProhibitBarewordFileHandles>

Write C<open my $fh, q{<}, $filename;> instead of C<open FH, q{<}, $filename;>. [Default severity 5]

=head2 L<InputOutput::ProhibitExplicitStdin|Perl::Mogrify::Transformer::InputOutput::ProhibitExplicitStdin>

Use "<>" or "<ARGV>" or a prompting module instead of "<STDIN>". [Default severity 4]

=head2 L<InputOutput::ProhibitInteractiveTest|Perl::Mogrify::Transformer::InputOutput::ProhibitInteractiveTest>

Use prompt() instead of -t. [Default severity 5]

=head2 L<InputOutput::ProhibitJoinedReadline|Perl::Mogrify::Transformer::InputOutput::ProhibitJoinedReadline>

Use C<local $/ = undef> or L<File::Slurp|File::Slurp> instead of joined readline. [Default severity 3]

=head2 L<InputOutput::ProhibitOneArgSelect|Perl::Mogrify::Transformer::InputOutput::ProhibitOneArgSelect>

Never write C<select($fh)>. [Default severity 4]

=head2 L<InputOutput::ProhibitReadlineInForLoop|Perl::Mogrify::Transformer::InputOutput::ProhibitReadlineInForLoop>

Write C<< while( $line = <> ){...} >> instead of C<< for(<>){...} >>. [Default severity 4]

=head2 L<InputOutput::ProhibitTwoArgOpen|Perl::Mogrify::Transformer::InputOutput::ProhibitTwoArgOpen>

Write C<< open $fh, q{<}, $filename; >> instead of C<< open $fh, "<$filename"; >>. [Default severity 5]

=head2 L<InputOutput::RequireBracedFileHandleWithPrint|Perl::Mogrify::Transformer::InputOutput::RequireBracedFileHandleWithPrint>

Write C<print {$FH} $foo, $bar;> instead of C<print $FH $foo, $bar;>. [Default severity 1]

=head2 L<InputOutput::RequireBriefOpen|Perl::Mogrify::Transformer::InputOutput::RequireBriefOpen>

Close filehandles as soon as possible after opening them. [Default severity 4]

=head2 L<InputOutput::RequireCheckedClose|Perl::Mogrify::Transformer::InputOutput::RequireCheckedClose>

Write C<< my $error = close $fh; >> instead of C<< close $fh; >>. [Default severity 2]

=head2 L<InputOutput::RequireCheckedOpen|Perl::Mogrify::Transformer::InputOutput::RequireCheckedOpen>

Write C<< my $error = open $fh, $mode, $filename; >> instead of C<< open $fh, $mode, $filename; >>. [Default severity 3]

=head2 L<InputOutput::RequireCheckedSyscalls|Perl::Mogrify::Transformer::InputOutput::RequireCheckedSyscalls>

Return value of flagged function ignored. [Default severity 1]

=head2 L<InputOutput::RequireEncodingWithUTF8Layer|Perl::Mogrify::Transformer::InputOutput::RequireEncodingWithUTF8Layer>

Write C<< open $fh, q{<:encoding(UTF-8)}, $filename; >> instead of C<< open $fh, q{{<:utf8}, $filename; >>. [Default severity 5]

=head2 L<Miscellanea::ProhibitFormats|Perl::Mogrify::Transformer::Miscellanea::ProhibitFormats>

Do not use C<format>. [Default severity 3]

=head2 L<Miscellanea::ProhibitTies|Perl::Mogrify::Transformer::Miscellanea::ProhibitTies>

Do not use C<tie>. [Default severity 2]

=head2 L<Miscellanea::ProhibitUnrestrictedNoCritic|Perl::Mogrify::Transformer::Miscellanea::ProhibitUnrestrictedNoCritic>

Forbid a bare C<## no critic> [Default severity 3]

=head2 L<Miscellanea::ProhibitUselessNoCritic|Perl::Mogrify::Transformer::Miscellanea::ProhibitUselessNoCritic>

Remove ineffective "## no critic" annotations. [Default severity 2]

=head2 L<Modules::ProhibitAutomaticExportation|Perl::Mogrify::Transformer::Modules::ProhibitAutomaticExportation>

Export symbols via C<@EXPORT_OK> or C<%EXPORT_TAGS> instead of C<@EXPORT>. [Default severity 4]

=head2 L<Modules::ProhibitConditionalUseStatements|Perl::Mogrify::Transformer::Modules::ProhibitConditionalUseStatements>

Avoid putting conditional logic around compile-time includes. [Default severity 3]

=head2 L<Modules::ProhibitEvilModules|Perl::Mogrify::Transformer::Modules::ProhibitEvilModules>

Ban modules that aren't blessed by your shop. [Default severity 5]

=head2 L<Modules::ProhibitExcessMainComplexity|Perl::Mogrify::Transformer::Modules::ProhibitExcessMainComplexity>

Minimize complexity in code that is B<outside> of subroutines. [Default severity 3]

=head2 L<Modules::ProhibitMultiplePackages|Perl::Mogrify::Transformer::Modules::ProhibitMultiplePackages>

Put packages (especially subclasses) in separate files. [Default severity 4]

=head2 L<Modules::RequireBarewordIncludes|Perl::Mogrify::Transformer::Modules::RequireBarewordIncludes>

Write C<require Module> instead of C<require 'Module.pm'>. [Default severity 5]

=head2 L<Modules::RequireEndWithOne|Perl::Mogrify::Transformer::Modules::RequireEndWithOne>

End each module with an explicitly C<1;> instead of some funky expression. [Default severity 4]

=head2 L<Modules::RequireExplicitPackage|Perl::Mogrify::Transformer::Modules::RequireExplicitPackage>

Always make the C<package> explicit. [Default severity 4]

=head2 L<Modules::RequireFilenameMatchesPackage|Perl::Mogrify::Transformer::Modules::RequireFilenameMatchesPackage>

Package declaration must match filename. [Default severity 5]

=head2 L<Modules::RequireNoMatchVarsWithUseEnglish|Perl::Mogrify::Transformer::Modules::RequireNoMatchVarsWithUseEnglish>

C<use English> must be passed a C<-no_match_vars> argument. [Default severity 2]

=head2 L<Modules::RequireVersionVar|Perl::Mogrify::Transformer::Modules::RequireVersionVar>

Give every module a C<$VERSION> number. [Default severity 2]

=head2 L<NamingConventions::Capitalization|Perl::Mogrify::Transformer::NamingConventions::Capitalization>

Distinguish different program components by case. [Default severity 1]

=head2 L<NamingConventions::ProhibitAmbiguousNames|Perl::Mogrify::Transformer::NamingConventions::ProhibitAmbiguousNames>

Don't use vague variable or subroutine names like 'last' or 'record'. [Default severity 3]

=head2 L<Objects::ProhibitIndirectSyntax|Perl::Mogrify::Transformer::Objects::ProhibitIndirectSyntax>

Prohibit indirect object call syntax. [Default severity 4]

=head2 L<References::ProhibitDoubleSigils|Perl::Mogrify::Transformer::References::ProhibitDoubleSigils>

Write C<@{ $array_ref }> instead of C<@$array_ref>. [Default severity 2]

=head2 L<RegularExpressions::ProhibitCaptureWithoutTest|Perl::Mogrify::Transformer::RegularExpressions::ProhibitCaptureWithoutTest>

Capture variable used outside conditional. [Default severity 3]

=head2 L<RegularExpressions::ProhibitComplexRegexes|Perl::Mogrify::Transformer::RegularExpressions::ProhibitComplexRegexes>

Split long regexps into smaller C<qr//> chunks. [Default severity 3]

=head2 L<RegularExpressions::ProhibitEnumeratedClasses|Perl::Mogrify::Transformer::RegularExpressions::ProhibitEnumeratedClasses>

Use named character classes instead of explicit character lists. [Default severity 1]

=head2 L<RegularExpressions::ProhibitEscapedMetacharacters|Perl::Mogrify::Transformer::RegularExpressions::ProhibitEscapedMetacharacters>

Use character classes for literal meta-characters instead of escapes. [Default severity 1]

=head2 L<RegularExpressions::ProhibitFixedStringMatches|Perl::Mogrify::Transformer::RegularExpressions::ProhibitFixedStringMatches>

Use C<eq> or hash instead of fixed-pattern regexps. [Default severity 2]

=head2 L<RegularExpressions::ProhibitSingleCharAlternation|Perl::Mogrify::Transformer::RegularExpressions::ProhibitSingleCharAlternation>

Use C<[abc]> instead of C<a|b|c>. [Default severity 1]

=head2 L<RegularExpressions::ProhibitUnusedCapture|Perl::Mogrify::Transformer::RegularExpressions::ProhibitUnusedCapture>

Only use a capturing group if you plan to use the captured value. [Default severity 3]

=head2 L<RegularExpressions::ProhibitUnusualDelimiters|Perl::Mogrify::Transformer::RegularExpressions::ProhibitUnusualDelimiters>

Use only C<//> or C<{}> to delimit regexps. [Default severity 1]

=head2 L<RegularExpressions::ProhibitUselessTopic|Perl::Mogrify::Transformer::RegularExpressions::ProhibitUselessTopic>

Don't use $_ to match against regexes. [Default severity 2]

=head2 L<RegularExpressions::RequireBracesForMultiline|Perl::Mogrify::Transformer::RegularExpressions::RequireBracesForMultiline>

Use C<{> and C<}> to delimit multi-line regexps. [Default severity 1]

=head2 L<RegularExpressions::RequireDotMatchAnything|Perl::Mogrify::Transformer::RegularExpressions::RequireDotMatchAnything>

Always use the C</s> modifier with regular expressions. [Default severity 2]

=head2 L<RegularExpressions::RequireExtendedFormatting|Perl::Mogrify::Transformer::RegularExpressions::RequireExtendedFormatting>

Always use the C</x> modifier with regular expressions. [Default severity 3]

=head2 L<RegularExpressions::RequireLineBoundaryMatching|Perl::Mogrify::Transformer::RegularExpressions::RequireLineBoundaryMatching>

Always use the C</m> modifier with regular expressions. [Default severity 2]

=head2 L<Subroutines::ProhibitAmpersandSigils|Perl::Mogrify::Transformer::Subroutines::ProhibitAmpersandSigils>

Don't call functions with a leading ampersand sigil. [Default severity 2]

=head2 L<Subroutines::ProhibitBuiltinHomonyms|Perl::Mogrify::Transformer::Subroutines::ProhibitBuiltinHomonyms>

Don't declare your own C<open> function. [Default severity 4]

=head2 L<Subroutines::ProhibitExcessComplexity|Perl::Mogrify::Transformer::Subroutines::ProhibitExcessComplexity>

Minimize complexity by factoring code into smaller subroutines. [Default severity 3]

=head2 L<Subroutines::ProhibitExplicitReturnUndef|Perl::Mogrify::Transformer::Subroutines::ProhibitExplicitReturnUndef>

Return failure with bare C<return> instead of C<return undef>. [Default severity 5]

=head2 L<Subroutines::ProhibitManyArgs|Perl::Mogrify::Transformer::Subroutines::ProhibitManyArgs>

Too many arguments. [Default severity 3]

=head2 L<Subroutines::ProhibitNestedSubs|Perl::Mogrify::Transformer::Subroutines::ProhibitNestedSubs>

C<sub never { sub correct {} }>. [Default severity 5]

=head2 L<Subroutines::ProhibitReturnSort|Perl::Mogrify::Transformer::Subroutines::ProhibitReturnSort>

Behavior of C<sort> is not defined if called in scalar context. [Default severity 5]

=head2 L<Subroutines::ProhibitSubroutinePrototypes|Perl::Mogrify::Transformer::Subroutines::ProhibitSubroutinePrototypes>

Don't write C<sub my_function (@@) {}>. [Default severity 5]

=head2 L<Subroutines::ProhibitUnusedPrivateSubroutines|Perl::Mogrify::Transformer::Subroutines::ProhibitUnusedPrivateSubroutines>

Prevent unused private subroutines. [Default severity 3]

=head2 L<Subroutines::ProtectPrivateSubs|Perl::Mogrify::Transformer::Subroutines::ProtectPrivateSubs>

Prevent access to private subs in other packages. [Default severity 3]

=head2 L<Subroutines::RequireArgUnpacking|Perl::Mogrify::Transformer::Subroutines::RequireArgUnpacking>

Always unpack C<@_> first. [Default severity 4]

=head2 L<Subroutines::RequireFinalReturn|Perl::Mogrify::Transformer::Subroutines::RequireFinalReturn>

End every path through a subroutine with an explicit C<return> statement. [Default severity 4]

=head2 L<TestingAndDebugging::ProhibitNoStrict|Perl::Mogrify::Transformer::TestingAndDebugging::ProhibitNoStrict>

Prohibit various flavors of C<no strict>. [Default severity 5]

=head2 L<TestingAndDebugging::ProhibitNoWarnings|Perl::Mogrify::Transformer::TestingAndDebugging::ProhibitNoWarnings>

Prohibit various flavors of C<no warnings>. [Default severity 4]

=head2 L<TestingAndDebugging::ProhibitProlongedStrictureOverride|Perl::Mogrify::Transformer::TestingAndDebugging::ProhibitProlongedStrictureOverride>

Don't turn off strict for large blocks of code. [Default severity 4]

=head2 L<TestingAndDebugging::RequireTestLabels|Perl::Mogrify::Transformer::TestingAndDebugging::RequireTestLabels>

Tests should all have labels. [Default severity 3]

=head2 L<TestingAndDebugging::RequireUseStrict|Perl::Mogrify::Transformer::TestingAndDebugging::RequireUseStrict>

Always C<use strict>. [Default severity 5]

=head2 L<TestingAndDebugging::RequireUseWarnings|Perl::Mogrify::Transformer::TestingAndDebugging::RequireUseWarnings>

Always C<use warnings>. [Default severity 4]

=head2 L<ValuesAndExpressions::ProhibitCommaSeparatedStatements|Perl::Mogrify::Transformer::ValuesAndExpressions::ProhibitCommaSeparatedStatements>

Don't use the comma operator as a statement separator. [Default severity 4]

=head2 L<ValuesAndExpressions::ProhibitComplexVersion|Perl::Mogrify::Transformer::ValuesAndExpressions::ProhibitComplexVersion>

Prohibit version values from outside the module. [Default severity 3]

=head2 L<ValuesAndExpressions::ProhibitConstantPragma|Perl::Mogrify::Transformer::ValuesAndExpressions::ProhibitConstantPragma>

Don't C<< use constant FOO => 15 >>. [Default severity 4]

=head2 L<ValuesAndExpressions::ProhibitEmptyQuotes|Perl::Mogrify::Transformer::ValuesAndExpressions::ProhibitEmptyQuotes>

Write C<q{}> instead of C<''>. [Default severity 2]

=head2 L<ValuesAndExpressions::ProhibitEscapedCharacters|Perl::Mogrify::Transformer::ValuesAndExpressions::ProhibitEscapedCharacters>

Write C<"\N{DELETE}"> instead of C<"\x7F">, etc. [Default severity 2]

=head2 L<ValuesAndExpressions::ProhibitImplicitNewlines|Perl::Mogrify::Transformer::ValuesAndExpressions::ProhibitImplicitNewlines>

Use concatenation or HEREDOCs instead of literal line breaks in strings. [Default severity 3]

=head2 L<ValuesAndExpressions::ProhibitInterpolationOfLiterals|Perl::Mogrify::Transformer::ValuesAndExpressions::ProhibitInterpolationOfLiterals>

Always use single quotes for literal strings. [Default severity 1]

=head2 L<ValuesAndExpressions::ProhibitLeadingZeros|Perl::Mogrify::Transformer::ValuesAndExpressions::ProhibitLeadingZeros>

Write C<oct(755)> instead of C<0755>. [Default severity 5]

=head2 L<ValuesAndExpressions::ProhibitLongChainsOfMethodCalls|Perl::Mogrify::Transformer::ValuesAndExpressions::ProhibitLongChainsOfMethodCalls>

Long chains of method calls indicate tightly coupled code. [Default severity 2]

=head2 L<ValuesAndExpressions::ProhibitMagicNumbers|Perl::Mogrify::Transformer::ValuesAndExpressions::ProhibitMagicNumbers>

Don't use values that don't explain themselves. [Default severity 2]

=head2 L<ValuesAndExpressions::ProhibitMismatchedOperators|Perl::Mogrify::Transformer::ValuesAndExpressions::ProhibitMismatchedOperators>

Don't mix numeric operators with string operands, or vice-versa. [Default severity 3]

=head2 L<ValuesAndExpressions::ProhibitMixedBooleanOperators|Perl::Mogrify::Transformer::ValuesAndExpressions::ProhibitMixedBooleanOperators>

Write C< !$foo && $bar || $baz > instead of C< not $foo && $bar or $baz>. [Default severity 4]

=head2 L<ValuesAndExpressions::ProhibitNoisyQuotes|Perl::Mogrify::Transformer::ValuesAndExpressions::ProhibitNoisyQuotes>

Use C<q{}> or C<qq{}> instead of quotes for awkward-looking strings. [Default severity 2]

=head2 L<ValuesAndExpressions::ProhibitQuotesAsQuotelikeOperatorDelimiters|Perl::Mogrify::Transformer::ValuesAndExpressions::ProhibitQuotesAsQuotelikeOperatorDelimiters>

Don't use quotes (C<'>, C<">, C<`>) as delimiters for the quote-like operators. [Default severity 3]

=head2 L<ValuesAndExpressions::ProhibitSpecialLiteralHeredocTerminator|Perl::Mogrify::Transformer::ValuesAndExpressions::ProhibitSpecialLiteralHeredocTerminator>

Don't write C< print <<'__END__' >. [Default severity 3]

=head2 L<ValuesAndExpressions::ProhibitVersionStrings|Perl::Mogrify::Transformer::ValuesAndExpressions::ProhibitVersionStrings>

Don't use strings like C<v1.4> or C<1.4.5> when including other modules. [Default severity 3]

=head2 L<ValuesAndExpressions::RequireConstantVersion|Perl::Mogrify::Transformer::ValuesAndExpressions::RequireConstantVersion>

Require $VERSION to be a constant rather than a computed value. [Default severity 2]

=head2 L<ValuesAndExpressions::RequireInterpolationOfMetachars|Perl::Mogrify::Transformer::ValuesAndExpressions::RequireInterpolationOfMetachars>

Warns that you might have used single quotes when you really wanted double-quotes. [Default severity 1]

=head2 L<ValuesAndExpressions::RequireNumberSeparators|Perl::Mogrify::Transformer::ValuesAndExpressions::RequireNumberSeparators>

Write C< 141_234_397.0145 > instead of C< 141234397.0145 >. [Default severity 2]

=head2 L<ValuesAndExpressions::RequireQuotedHeredocTerminator|Perl::Mogrify::Transformer::ValuesAndExpressions::RequireQuotedHeredocTerminator>

Write C< print <<'THE_END' > or C< print <<"THE_END" >. [Default severity 3]

=head2 L<ValuesAndExpressions::RequireUpperCaseHeredocTerminator|Perl::Mogrify::Transformer::ValuesAndExpressions::RequireUpperCaseHeredocTerminator>

Write C< <<'THE_END'; > instead of C< <<'theEnd'; >. [Default severity 2]

=head2 L<Variables::ProhibitAugmentedAssignmentInDeclaration|Perl::Mogrify::Transformer::Variables::ProhibitAugmentedAssignmentInDeclaration>

Do not write C< my $foo .= 'bar'; >. [Default severity 4]

=head2 L<Variables::ProhibitConditionalDeclarations|Perl::Mogrify::Transformer::Variables::ProhibitConditionalDeclarations>

Do not write C< my $foo = $bar if $baz; >. [Default severity 5]

=head2 L<Variables::ProhibitEvilVariables|Perl::Mogrify::Transformer::Variables::ProhibitEvilVariables>

Ban variables that aren't blessed by your shop. [Default severity 5]

=head2 L<Variables::ProhibitLocalVars|Perl::Mogrify::Transformer::Variables::ProhibitLocalVars>

Use C<my> instead of C<local>, except when you have to. [Default severity 2]

=head2 L<Variables::ProhibitMatchVars|Perl::Mogrify::Transformer::Variables::ProhibitMatchVars>

Avoid C<$`>, C<$&>, C<$'> and their English equivalents. [Default severity 4]

=head2 L<Variables::ProhibitPackageVars|Perl::Mogrify::Transformer::Variables::ProhibitPackageVars>

Eliminate globals declared with C<our> or C<use vars>. [Default severity 3]

=head2 L<Variables::ProhibitPerl4PackageNames|Perl::Mogrify::Transformer::Variables::ProhibitPerl4PackageNames>

Use double colon (::) to separate package name components instead of single quotes ('). [Default severity 2]

=head2 L<Variables::ProhibitPunctuationVars|Perl::Mogrify::Transformer::Variables::ProhibitPunctuationVars>

Write C<$EVAL_ERROR> instead of C<$@>. [Default severity 2]

=head2 L<Variables::ProhibitReusedNames|Perl::Mogrify::Transformer::Variables::ProhibitReusedNames>

Do not reuse a variable name in a lexical scope [Default severity 3]

=head2 L<Variables::ProhibitUnusedVariables|Perl::Mogrify::Transformer::Variables::ProhibitUnusedVariables>

Don't ask for storage you don't need. [Default severity 3]

=head2 L<Variables::ProtectPrivateVars|Perl::Mogrify::Transformer::Variables::ProtectPrivateVars>

Prevent access to private vars in other packages. [Default severity 3]

=head2 L<Variables::RequireInitializationForLocalVars|Perl::Mogrify::Transformer::Variables::RequireInitializationForLocalVars>

Write C<local $foo = $bar;> instead of just C<local $foo;>. [Default severity 3]

=head2 L<Variables::RequireLexicalLoopIterators|Perl::Mogrify::Transformer::Variables::RequireLexicalLoopIterators>

Write C<for my $element (@list) {...}> instead of C<for $element (@list) {...}>. [Default severity 5]

=head2 L<Variables::RequireLocalizedPunctuationVars|Perl::Mogrify::Transformer::Variables::RequireLocalizedPunctuationVars>

Magic variables should be assigned as "local". [Default severity 4]

=head2 L<Variables::RequireNegativeIndices|Perl::Mogrify::Transformer::Variables::RequireNegativeIndices>

Negative array index should be used. [Default severity 4]


=head1 VERSION

This is part of L<Perl::Mogrify|Perl::Mogrify> version 1.116.


=head1 AUTHOR

Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>


=head1 COPYRIGHT

Copyright (c) 2005-2011 Imaginative Software Systems.  All rights reserved.

This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.  The full text of this license
can be found in the LICENSE file included with this module.

=cut
