
=head1 NAME

Perl::Mogrify::TransformerSummary - Descriptions of the Transformer modules included with L<Perl::Mogrify|Perl::Mogrify> itself.


=head1 DESCRIPTION

The following Transformer modules are distributed with Perl::Mogrify. (There are
additional Policies that can be found in add-on distributions.)  The Transformer
modules have been categorized according to the table of contents in Damian
Conway's book B<Perl Best Practices>. Since most coding standards take the
form "do this..." or "don't do that...", I have adopted the convention of
naming each module C<RequireSomething> or C<ProhibitSomething>.  Each Transformer
is listed here with its default severity.  If you don't agree with the default
severity, you can change it in your F<.perlmogrifyrc> file (try C<perlmogrify
--profile-proto> for a starting version).  See the documentation of each
module for its specific details.


=head1 POLICIES

=head2 L<BuiltinFunctions::ProhibitBooleanGrep|Perl::Mogrify::Transformer::BuiltinFunctions::ProhibitBooleanGrep>

Use C<List::MoreUtils::any> instead of C<grep> in boolean context. [Default severity 2]

=head2 L<Perl::Mogrify::Transformer::FormatConstants>

Use C<our constant @EXPORT_OK = qw (a b c)> instead of C<Readonly our @EXPORT_OK => qw(a b c)>.
[Mandatory]

=head2 L<Perl::Mogrify::Transformer::BasicTypes::Integers::FormatOctalLiterals>

Use C<<:8<1234567>>> instead of C<01234567>.
[Mandatory]

=head2 L<Perl::Mogrify::Transformer::BasicTypes::Integers::FormatBinaryLiterals>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::BasicTypes::Integers::FormatHexLiterals>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::BasicTypes::Rationals::FormatRationals>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::BasicTypes::Strings::FormatRegexp>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::BasicTypes::Strings::FormatHereDocs>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::BasicTypes::Strings::FormatHereDocs>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::BasicTypes::Strings::FormatRegexp>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::BasicTypes::Strings::FormatShellStrings>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::BasicTypes::Strings::InterpolatedBraces>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::BasicTypes::Strings::InterpolatedCase>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::FormatBuiltins>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::Pragmas::FormatPragmas>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::CompoundStatements::FormatConditionals>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::CompoundStatements::FormatWhens>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::CompoundStatements::FormatLoops>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::CompoundStatements::FormatUntils>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::CompoundStatements::FormatGivenWhens>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::CompoundStatements::FormatMapGreps>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::CompoundStatements::SwapForArguments>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::Arrays::FormatArrayQws>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::FormatSpecialLiterals>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::Variables::FormatHashKeys>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::Variables::FormatSigils>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::Variables::FormatSpecialVariables>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::Operators::FormatUnaryOperators>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::Operators::FormatTernaryOperators>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::Operators::FormatBinaryOperators>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::Operators::FormatCircumfixOperators>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::Packages::FormatPackageDeclarations>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::Packages::FormatPackageUsages>

[Mandatory]

=head2 L<Perl::Mogrify::Transformer::References::FormatDereferences>

[Mandatory]

=head1 VERSION

This is part of L<Perl::Mogrify|Perl::Mogrify> version 1.116.


=head1 AUTHOR

Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>


=head1 COPYRIGHT

Copyright (c) 2005-2011 Imaginative Software Systems.  All rights reserved.

This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.  The full text of this license
can be found in the LICENSE file included with this module.

=cut
