## name unchanged
## parms {}
## failures 0
## cut
## I'm not sure any special variables *didn't* get renamed...
#-->
## I'm not sure any special variables *didn't* get renamed...
#------------------------------------------------------------------------------

## name transform
## parms {}
## failures 0
## cut
print STDOUT;
print $`;
print $&;
print @+;
#-->
print $*OUT;
print $/.prematch
print ~$/;
print (map {.from},$/[*]);
